### ISSUE TITLE
Implement atomic design in the styleguide

### ISSUE THREAD

**Issue by jeremiak** [18F/cg-style#115]
To make the implementation of atomic design easier throughout cloud.gov projects by using Fractal, a component library framework.

Acceptance criteria:
- [ ]  As a user, I should be able to find and implement atomic designs from cloud.gov styles into my project.
- [ ] As a user, I should have sample code options available to me so that I can easily use cloud.gov atomic designs on my chosen web framework.
- [x] As a user, I should be able to visit a url to view these code samples and documentation.

**Comment by juliasolorzano** [comment]
Work started here: https://github.com/18F/cg-style/tree/je-add_atomic_library

**Comment by juliasolorzano** [comment]
@vz3 @thisisdano quick check-in to see what you all think the next steps should be in implementing the pattern library. We have the ground work ready for adding components. I made note of a possible pattern to add [here](https://github.com/18F/cg-design/issues/5#issuecomment-240788665) and would be great to get further direction for next steps 😄 

Also, [here is the current state of the pattern library](http://federalist.18f.gov.s3-website-us-east-1.amazonaws.com/site/18F/cg-style/) for your reference.

**Comment by thisisdano** [comment]
The new pattern library should probably include the existing patterns from `cg-style` — that's probably a good place to start. Does anyone have a build of fractal running that includes all the USWDS? That would also be a good starting point — and helpful for others in the future.

**Comment by thisisdano** [comment]
And, while I'm happy to use standard atomic taxonomy, I've also thought about how to organize atomic design here:

https://docs.google.com/a/gsa.gov/spreadsheets/d/1jz_R-92lRCUcOqzHBB9D-5AQvO6U7fZHJ_AKMChIkXM/edit?usp=sharing

Based on GE's Predix system: https://medium.com/ge-design/ges-predix-design-system-8236d47b0891#.rtdu7tkc9
And on stuff like Buzzfeed's low-level framework, Solid: http://solid.buzzfeed.com/
Which is, itself, based on basscss: http://www.basscss.com/

But, at the end of the day, it probably doesn't matter how everything looks and is organized, as long as it's there in some order or another. The flexible Solid-style, low-level framework–based design system is a pipe dream I have for USWDS, but I don't ever see it happening, realistically.

**Comment by vz3** [comment]
Let's start with type hierarchy, palette, and logo for now. I would hold off on USWDS elements for now.

**Comment by juliasolorzano** [comment]
@thisisdano @vz3 based on today's discussion, the next steps are adding the Sketch and/or Invision file(s) to this issue for us to start building out the patterns. I'll work on upgrading to the latest version of Fractal in the meantime 🎉
