### ISSUE TITLE
Upgrade to newest version of WDS

### ISSUE THREAD

**Issue by msecret** [18F/cg-style#123]
In order for 18F developers to use cg-style and receive the newest fixes from WDS, cg-style should be using the latest version of WDS rather then an old branch.

Acceptance criteria
- [x] cg-style should be install WDS directly from npm
- [x] cg-style should be using version of WDS higher then `0.10.0`.
- [x] cg-docs should be upgraded to newest version of cg-style with no breaking changes
- [x] cg-dashboard should be upgraded to newest version of cg-style with no breaking changes
- [x] cg-landing should be upgraded to newest version of cg-style with no breaking changes.

**Comment by jeremiak** [comment]
Criteria:
- [cg-style](https://github.com/18F/cg-style/releases/tag/1.0.0)
- [cg-docs](https://github.com/18F/cg-docs/blob/master/package.json#L36)
- [cg-dashboard](https://github.com/18F/cg-dashboard/commit/d160eda66c545f41de1e7017a7ff4da84bbf5c27)
- [cg-landing](https://github.com/18F/cg-landing/blob/master/Gemfile.lock#L15)
