### ISSUE TITLE
Upgrade to v0.12.1 of the Web Design Standards

### ISSUE THREAD

**Issue by juliasolorzano** [18F/cg-style#144]
As a designer or developer, I want access to current WDS features including search, headers, and navigation structure.

Updating `cg-style` to leverage v0.12.1 of the Standards for the new headers code.

Acceptance criteria
- [x] cg-style should be install WDS directly from npm
- [x] cg-style should be using version of WDS higher then `0.12.1`.
- [x] cg-docs should be upgraded to newest version of cg-style with no breaking changes
- [x] cg-dashboard should be upgraded to newest version of cg-style with no breaking changes
- [x] cg-landing should be upgraded to newest version of cg-style with no breaking changes.

**Comment by suprenant** [comment]
@juliaelman I added a value statement so we can track why we're doing this. Please update if you feel it needs to be clearer!

**Comment by juliasolorzano** [comment]
@suprenant perfect - thanks!

**Comment by juliasolorzano** [comment]
@vz3 @thisisdano there is a slight change in the list styles on the Dashboard. See the screenshots below for reference and let me know how/if you would like them to change:

## CURRENT DASHBOARD

![screen shot 2016-09-13 at 11 58 50 am](https://cloud.githubusercontent.com/assets/955558/18481341/df1c1872-79a9-11e6-8165-c70151ff79b4.png)

## UPGRADED DASHBOARD TO USE USWDS V0.12.1

![screen shot 2016-09-13 at 11 58 40 am](https://cloud.githubusercontent.com/assets/955558/18481324/cd9cacb0-79a9-11e6-8db5-f927413165ef.png)

**Comment by juliasolorzano** [comment]
@vz3 @thisisdano the cloud.gov landing page also had a few changes with the upgrade. The updated primary color effects a few things here and have outlined these changes with specific screenshots below:

## CURRENT CG LANDING PAGE

![screen shot 2016-09-13 at 12 57 24 pm](https://cloud.githubusercontent.com/assets/955558/18483381/c909dc06-79b1-11e6-9048-405501dd5a44.png)

![screen shot 2016-09-13 at 12 58 22 pm](https://cloud.githubusercontent.com/assets/955558/18483392/d3c382be-79b1-11e6-854f-65b669571ac1.png)

## UPGRADED CG LANDING TO USE USWDS V0.12.1

![screen shot 2016-09-13 at 12 57 18 pm](https://cloud.githubusercontent.com/assets/955558/18483422/f0c1c4b6-79b1-11e6-9fb7-f860dbcb55af.png)

![screen shot 2016-09-13 at 12 58 15 pm](https://cloud.githubusercontent.com/assets/955558/18483425/f4672e1c-79b1-11e6-8b4c-93e905ba1934.png)

**Comment by msecret** [comment]
I have a feeling the color change was caused by me in a previous PR

**Comment by thisisdano** [comment]
I don't think I can even see the differences in the list style. Bullet style, minor padding, and link color? I don't think there's anything to modify additionally.

(Any now that I look closely at this, I'm slightly surprised we have the ol' purple `:visited` style. Old school!)

**Comment by juliasolorzano** [comment]
@msecret no worries and thanks for clarifying!

@thisisdano thanks for your feedback! The bullets in the lists have a slightly different style and wanted to run by you and Victor to make sure it looks ok. Sounds like that's a 👍  from you and will check-in with @vz3 too.

**Comment by vz3** [comment]
I think the glyph contrast is a problem with the blue on blue. otherwise 👍 here. I like the heavier headers here.

**Comment by juliasolorzano** [comment]
Pull request opened here: https://github.com/18F/cg-landing/pull/95

Once this is merged in, we should be GTG to merge in https://github.com/18F/cg-style/pull/147
