### ISSUE TITLE
watch task sometimes runs over itself and dies

### ISSUE THREAD

**Issue by adborden** [18F/cg-style#166]
```
remote: Total 136 (delta 16), reused 126 (delta 14), pack-reused 0
Receiving objects: 100% (136/136), 1.24 MiB | 114.00 KiB/s, done.
fatal: unable to open /home/adborden/projects/cg/cg-style/gem/.git/objects/pack/tmp_pack_yVFjip: No such file or directory
fatal: index-pack failed
```

Here's the log https://gist.github.com/adborden/766d7e61333d3dc0eb7e44970d40d788
It looks like a `git clone` for `./gem` is already in progress, so then we `rm -rf ./gem` while the clone is in progress.

Repro
1. `npm run watch`
2.  Save your `scss` file over and over a handful of times.

**Comment by msecret** [comment]
This will be fixed with removing the gem repo and part of build process.
