### ISSUE TITLE
Move pattern library to its own static app

### ISSUE THREAD

**Issue by adborden** [18F/cg-style#177]
Our pattern library is currently at https://pages.18f.gov/cg-style but there's a slow movement to get all the 18f-pages onto federalist. This also gives us the ability to customize the domain.

PR https://github.com/18F/cg-style/pull/176 gives us a deploy script which pushes a static site. It's pretty simple to move this from 18f-pages to federalist simply by adding the `cg-style` repo to federalist with `18f-pages` as the custom branch. Then we only need to [add a custom domain](https://github.com/18F/federalist-docs/blob/master/pages/how-federalist-works/custom-urls.md) to host it at something like `cg-style.apps.cloud.gov`.

As a stretch, it would be great to document this in the federalist docs so folks moving other 18f-pages have simple instructions on how to do it.

**Comment by dlapiduz** [comment]
@adborden Would you rather use federalist or just push it to a CF app?

**Comment by dlapiduz** [comment]
Doing a concourse build for that should be fairly straightforward and we keep our dependencies low.

**Comment by adborden** [comment]
@dlapiduz hmm, that is a great point. Let me think about that.

**Comment by adborden** [comment]
BTW, what is concourse, it's not mentioned in the cloud.gov docs very much.

**Comment by dlapiduz** [comment]
I think we need a navigator "team" in concourse and do some talks/demo about it /cc @LinuxBozo @mogul what do you think?

**Comment by suprenant** [comment]
@msecret can you please accept this one? I'm not sure the best way to do so myself at the moment.

**Comment by mogul** [comment]
@dlapiduz Sorry for the delay... Not sure what you're intending here, can you explain more?

**Comment by dlapiduz** [comment]
Creating a team in concourse so we can have the front end pipelines with different access level from the back end ones.

**Comment by LinuxBozo** [comment]
@dlapiduz Team has been created: `navigator`.  #cloud-gov-navigator channel notified. For now, only `cg-site` pipeline is defined in that team. Will definitely need to set aside time for further training/discussion.

**Comment by rogeruiz** [comment]
✋ I can help walk Navigator through Concourse as well.

@adborden Take a look at these links
- http://concourse.ci/flight-school.html
- http://concourse.ci/tutorials.html
