### ISSUE TITLE
Remove Jekyll documentation

### ISSUE THREAD

**Issue by adborden** [18F/cg-style#178]
I looked through the existing documentation but don't see anything particularly useful to port to the pattern library. I think as we work with building new components or updating existing components, they can be added to the pattern library.

- [ ] Remove jekyll documentation
- [ ] Remove jekyll dependencies
- [ ] Remove jekyll references from README

Acceptance criteria:
- [x] Documentation contains no references to Jekyll
- [x] Dependencies on Jekyll are not able to be found
- [x] README contains no references to Jekyll
- [x] CONTRIBUTING contains a note that adding/updating UI components should also require that you add/update the component in the pattern library

**Comment by suprenant** [comment]
@adborden I added acceptance criteria – can you please update if you feel they should be clearer?

**Comment by adborden** [comment]
:+1: thanks, looks great. I added one note about adding a line to the CONTRIBUTING doc.
