### ISSUE TITLE
Code examples in content should be differentiated from other content

### ISSUE THREAD

**Issue by msecret** [18F/cg-style#19]
The content in the `<code>` blocks on some content pages should likely have a different background color and some spacing separation to ensure they're visually separated from surrounding content. Example here: https://docs-staging.apps.cloud.gov/ops/creating-a-local-dev-environment-in-Virtual-Box/

**Comment by jeremiak** [comment]
Does this issue refer only to code examples on the documentation site or does it mean changing the style guide so that sites that include it get styled code examples?

If it is the former, I think this should be closed as of 4f1f0ed223d67b22dc0d6e95a00a982d40eae77c

**Comment by msecret** [comment]
I think it means changing the style guide so sites that include it get styled code examples.
