### ISSUE TITLE
npm run watch does not copy assets to pattern library build

### ISSUE THREAD

**Issue by adborden** [18F/cg-style#202]
It would be nice when developing on the pattern library to use `npm run watch` so changes to cg-style styles are automatically picked up in the pattern library. Currently an extra step `npm run build-library` is necessary to pick up the changes.

**Comment by suprenant** [comment]
Marco and Aaron may have a fix here.

**Comment by suprenant** [comment]
@adborden sounds like this may be somewhat in progress. Do you want to groom this so we can tackle in this coming sprint?

**Comment by suprenant** [comment]
@adborden looks like this might be addressed. Feel free to close up if that's the case.

**Comment by adborden** [comment]
Yes, and @thisisdano says it's working well :)
