### ISSUE TITLE
The color-coded pill UI should be a repeatable pattern

### ISSUE THREAD

**Issue by msecret** [18F/cg-style#220]
There's many places on the site that use the pill on the left side of UI as a status. This could be repeatable with a component or a mixin.

**Comment by line47** [comment]
I'm working on this as part of https://github.com/18F/cg-dashboard/issues/786

**Comment by suprenant** [comment]
@line47 if this is WIP, let's move it into In Progress

**Comment by line47** [comment]
@msecret I'd like to have a quick conversation with you about this.

**Comment by adborden** [comment]
Looks great https://styleguide.fr.cloud.gov/components/detail/status-pill.html
