### ISSUE TITLE
Local installation errors when installing with cg-landing repository

### ISSUE THREAD

**Issue by mrengy** [18F/cg-style#59]
I'm trying to install the cg-landing project locally in order to try and resolve [this issue](https://github.com/18F/cg-landing/issues/43).

I originally opened an [issue in the cg-landing project](https://github.com/18F/cg-landing/issues/62), but I haven't heard back in a few days and thought it might be more relevant to post here also, as I'm getting the error with the cg-style installation.

I followed the instructions at an [updated Readme file for cg-style - in a pending pull request](https://github.com/18F/cg-landing/blob/ms-update_docs/README.md).
1. Ran `gem install github-pages`
2. Ran `jekyll serve --baseurl='' -w`
3. I already have the cg-style repository cloned.
4. From the cg-style directory, I ran `npm install cloudgov-style --save` and then got a bunch of errors in the Terminal, starting with:

> cc1plus: error: unrecognized command line option "-std=c++11"
> cc1plus: error: unrecognized command line option "-stdlib=libc++"
> make: **\* [Release/obj.target/libsass/src/libsass/src/ast.o] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2

Here's the [output from the Terminal](https://gist.github.com/mrengy/10bc099471b3541ab1d6e2fae1c70084).

And the [full npm-debug.log file](https://gist.github.com/mrengy/e5aca026b266b17f48cff4b2cdc126ce).

I'm on Mac OS 10.6, node v4.4.3, npm v2.15.1
Thanks for any insight.

**Comment by msecret** [comment]
Hey @mrengy, I've attempted to make the install instructions a little clearer in this PR: https://github.com/18F/cg-style/pull/61. One issue that I see: you shouldn't need to run `npm install cloudgov-style --save` from the cg-style directory. This would be trying to install `cg-style` into `cg-style`. If you have `cg-style` cloned, it should be ready to use. There could be another issue but try continuing the instructions without running the npm install command first. I also think you should follow the [Development and contributing setup](https://github.com/18F/cg-style/blob/ms-instructions/README.md#development-and-contributing-setup) instructions as that's what you're going for.

**Comment by msecret** [comment]
In case you get stuck again with a similar error after trying to run `npm install` and `npm run build` in the `cg-style` project, here is more information:

I think another problem could have to do with not having xcode (a development environment for osx) installed, so npm is unable to compile c++ code. It's unfortunate that there are npm modules that require a c++ development environment to be setup, but it's something that can be common in the npm packages land. In the future, we can look into limiting modules that require a c++ environment, but for the time being it will be required. I've added it to the PR as well.

**Comment by mrengy** [comment]
Thanks for the revisions and the follow-up. 

I tried again:
1. From the cg-landing repository, I ran `gem install github-pages`
2. From the cg-landing repository, I ran `jekyll serve --baseurl='' -w`
3. From the cg-style repository, I ran `npm install`

Got multiple warnings and errors. Last error was

> npm ERR! EEXIST: file already exists, symlink '../gulp-cli/bin/gulp.js' -> '/Applications/MAMP/htdocs/cg-style/node_modules/.bin/gulp'
> File exists: ../gulp-cli/bin/gulp.js
> Move it away, and try again. 

Here's the [full terminal output at that point](https://gist.github.com/mrengy/a706d011efddac0be1be81c0d45dedfc).

I found a gulp.js file, though it wasn't exactly where that error message said it was. It was at `/Applications/MAMP/htdocs/cg-style/node_modules/gulp/bin` rather than `/Applications/MAMP/htdocs/cg-style/node_modules/.bin/gulp`. I moved it out of that directory to my desktop anyway.
1. I ran `npm install` again

Got different errors, starting with

> make: **\* [Release/obj.target/libsass/src/libsass/src/ast.o] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/Applications/MAMP/htdocs/cg-style/node_modules/node-sass/node_modules/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:87:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> gyp ERR! System Darwin 10.8.0
> gyp ERR! command "/usr/local/bin/node" "/Applications/MAMP/htdocs/cg-style/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
> gyp ERR! cwd /Applications/MAMP/htdocs/cg-style/node_modules/node-sass
> gyp ERR! node -v v4.4.3
> gyp ERR! node-gyp -v v3.3.1
> gyp ERR! not ok 
> Build failed

Here's the [full terminal output then](https://gist.github.com/mrengy/040be14314cf96c8102ae3acdf0937e4).
1. Also, I ran `npm run build`
   and unsurprisingly got [more errors](https://gist.github.com/mrengy/46a6425921b86d0842728e0fd7f64615).

Here is my [npm-debug.log](https://gist.github.com/mrengy/dcd9d1e97b642f89c1ec804371caeffc) file.

Also, correct, I don't have Xcode installed due to the amount of hard drive space it takes up. I did install [GCC](https://gcc.gnu.org/), however. Is there a way to get this to work with GCC instead?

**Comment by msecret** [comment]
@mrengy looking at these errors:

```
Error: dlopen(/Applications/MAMP/htdocs/cg-style/node_modules/node-sass/vendor/darwin-x64-46/binding.node, 1): Symbol not found: __ZNKSt3__119__shared_weak_count13__get_deleterERKSt9type_info
  Referenced from: /Applications/MAMP/htdocs/cg-style/node_modules/node-sass/vendor/darwin-x64-46/binding.node
```

This error is saying you missing an include file in your system so gcc can't compile the c++ program. This is _likely_ something that would be fixed by installing xcode, as it installs a lot of the common includes that are needed by c++ programs. I'm not precisely sure what's missing, I tried to search but couldn't turn anything up.

```
Error: Can't run /Developer/usr/bin/xcodebuild (no such file).
```

It looks like node is looking for an xcode build configuration file of some sort, which isn't available because xcode isn't installed.

So the program which is failing is [node-gyp](https://github.com/nodejs/node-gyp) which is an addon to node that allows it to compile c/c++ programs. It specifically says that xcode is a dependency on osx. You could potentially try and get `node-gyp` working without xcode by installing the various missing dependencies and possibly some build configuration files. I probably wouldn't recommend that unless you're comfortable with building c++ programs on darwin. Otherwise, I'd suggest to try and install xcode. 

You can also search around to see if anybody has run node-gyp without xcode and has written about it. I took a look and wasn't able to find anything, but that doesn't mean it hasn't been done.

**Comment by mrengy** [comment]
All right. Well thanks a lot for your continued help. Seems like a dead end since I don't have the hard drive space to spare for XCode. I'll look into another project to contribute to.

**Comment by dogweather** [comment]
@mrengy Usually when "XCode" is a requirement, what's actually meant is the xcode cli tools which is a much smaller download. I install these via [Homebrew](http://brew.sh/) which requires them. 

Caveat, I haven't actually tried to get the dev environment running for this particular repo.

**Comment by msecret** [comment]
@dogweather thanks so much! I wasn't aware that was possible. I hope that solution could work for you @mrengy

**Comment by mrengy** [comment]
Thanks @dogweather and @msecret . Great idea. I just tried it. Here's how it went:
1. I uninstalled GCC following [these directions](http://magnemg.tumblr.com/post/113251602430/how-to-completely-uninstall-osx-gcc-installer) up to the heading of "Download only the necessary OSX Mavericks usr/bin files here" (which wasn't relevant to me since this is on Mac OS 10.6)
2. I [installed Xcode Command Line tools by modifying the disk image](http://kitcambridge.tumblr.com/post/17778742499/installing-the-xcode-command-line-tools-on-snow).
3. From the cg-landing repository, I ran `gem install github-pages`
4. From the cg-landing repository, I ran `jekyll serve --baseurl='' -w`
5. From the cg-style repository, I ran `npm install` and got the following:

> mike-engs-computer-2:cg-style mikeeng$ npm install
> npm WARN package.json cloudgov-style@0.3.4 license should be a valid SPDX license expression
> npm ERR! git fetch -a origin (https://git@github.com/18F/web-design-standards.git) dyld: Library not loaded: /usr/lib/libcurl.4.dylib
> npm ERR! git fetch -a origin (https://git@github.com/18F/web-design-standards.git)   Referenced from: /usr/libexec/git-core/git-remote-https
> npm ERR! git fetch -a origin (https://git@github.com/18F/web-design-standards.git)   Reason: Incompatible library version: git-remote-https requires version 7.0.0 or later, but libcurl.4.dylib provides version 6.0.0
> npm ERR! Darwin 10.8.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
> npm ERR! node v4.4.3
> npm ERR! npm  v2.15.1
> npm ERR! code 128
> 
> npm ERR! Command failed: git fetch -a origin
> npm ERR! dyld: Library not loaded: /usr/lib/libcurl.4.dylib
> npm ERR!   Referenced from: /usr/libexec/git-core/git-remote-https
> npm ERR!   Reason: Incompatible library version: git-remote-https requires version 7.0.0 or later, but libcurl.4.dylib provides version 6.0.0
1. I googled those errors and found a [suggestion to see whether a couple of different type commands show the same file path](http://unix.stackexchange.com/a/215808/12027). For me, both commands returned `curl is /usr/bin/curl`. Wasn't sure what to do next.
2. Based on [this other suggestion](https://github.com/Homebrew/legacy-homebrew/issues/15698#issuecomment-136441330), I ran `export PATH="$(brew --prefix git)/bin:$PATH"` again and then ran `npm install` again, and I got exactly the same errors.
3. I ran `brew install git` . This downloaded and seemed to successfully install git 2.8.1.
4. I ran `npm install` again and got the same errors.
5. Interestingly, `git --version` returned `git version 1.7.7.5 (Apple Git-26)` instead of 2.8.1.
6. I tried [this approach](http://apple.stackexchange.com/a/93179/15177). Here are the contents of [my .bash_profile file](https://gist.github.com/mrengy/4649886bd70220bba8513f4ddd37b1d8).
7. Still, `git --version` returns `git version 1.7.7.5 (Apple Git-26)`

This is getting a little nuts, and it may be not worth the trouble at this point, but let me know if you have any ideas.

Here are the [contents of my npm.debug.log file](https://gist.github.com/mrengy/a6316da70cea04157c77d6478f577ee1).

**Comment by msecret** [comment]
This issue should be kept open as incentive and explanation of simplifying installation for contributors.
