### ISSUE TITLE
USA Disclaimer link text color isn't 508 compliant

### ISSUE THREAD

**Issue by jeremiak** [18F/cg-style#68]
As pointed out in 18f/cg-landing#58, the link text color in the `.usa-disclaimer` component has a contrast ratio (against the background) of `4.03:1` when it needs to be `4.5:1`. `HTML_CodeSniffer` recommends using a background color of `#fefefe` but that is quite dark and would introduce contrast issues with the rest of the text.

We need @thisisdano or @vz3 to recommend another color for the disclaimer link text.

Current background color: `#f1f1f1`
Current link text color: `#277cb2`

Screenshot:
![](https://s3.amazonaws.com/f.cl.ly/items/102j0g410g0u432I1B14/Screen%20Shot%202016-05-12%20at%201.29.46%20PM.png?v=cc16dfa5)

**Comment by jeremiak** [comment]
This same issue applies to the contents of `.usa-footer`

**Comment by thisisdano** [comment]
We could try lighten the background gray in both sections to `#f3f3f3` and replace the current blue with `#0D6D9D`.

That gives us a ratio of 5.3:1.

I might also suggest bumping up the weight of the `.usa-disclaimer` text to 400.

**Comment by vz3** [comment]
I'd recommend we pull the values from the USWDS banner
#f1f1f1 (light grey) on #0071bc (link color)
https://standards.usa.gov/visual-style/#text-accessibility

assuming that gets us to the right place.

**Comment by msecret** [comment]
Acceptance criteria:
- [ ] The background color should be #f1f1f1.
- [ ] The text color should be black.
- [ ] The link color should be #0071bc.
