### ISSUE TITLE
table head doesn't align with the body

### ISSUE THREAD

**Issue by afeld** [18F/cg-style#72]
As seen on the [continuous deployment](https://docs.cloud.gov/apps/continuous-deployment/#wercker:f004fb092dc02b12177935ccc2735e2f) page of the docs:

<img width="705" alt="screen shot 2016-05-13 at 4 21 51 pm" src="https://cloud.githubusercontent.com/assets/86842/15260799/d8e8b548-1926-11e6-96f7-bae28f67e744.png">

Confirmed that it's not an issue with the Markdown.

**Comment by msecret** [comment]
This was fixed
